<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net11.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>BetterDns.Gui</RootNamespace>
    <AssemblyName>BetterDNS</AssemblyName>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\BetterDNS.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BetterDns.Core/BetterDns.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\BetterDNS.ico" />
    <Resource Include="Assets\BetterDNS.png" />
  </ItemGroup>
</Project>
